In [54]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


from sklearn.model_selection import train_test_split

from sklearn.linear_model import LinearRegression, SGDRegressor

from sklearn.preprocessing import PolynomialFeatures, StandardScaler

from sklearn.metrics import r2_score

from sklearn.pipeline import Pipeline

In [55]:
from google.colab import drive
drive.mount('/content/gdrive/', force_remount= True)

Mounted at /content/gdrive/

In [56]:
df = pd.read_csv("/content/gdrive/My Drive/ML_practical/Linear_Regression_multivariate/realest.csv")
df.drop(df.tail(1).index, inplace = True)
df

     Price  Bedroom   Space  Room   Lot     Tax  Bathroom  Garage  Condition
0     53.0      2.0   967.0   5.0  39.0   652.0       1.5     0.0        0.0
1     55.0      2.0   815.0   5.0  33.0  1000.0       1.0     2.0        1.0
2     56.0      3.0   900.0   5.0  35.0   897.0       1.5     1.0        0.0
3     58.0      3.0  1007.0   6.0  24.0   964.0       1.5     2.0        0.0
4     64.0      3.0  1100.0   7.0  50.0  1099.0       1.5     1.5        0.0
..     ...      ...     ...   ...   ...     ...       ...     ...        ...
151   42.0      3.0   585.0   5.0  50.0   713.0       1.0     0.0        0.0
152   44.0      3.0   820.0   5.0  27.0     NaN       1.0     0.0        1.0
153   43.0      2.0   593.0   4.0  30.0   465.0       2.0     1.0        0.0
154   53.0      3.0   716.0   6.0  30.0   585.0       1.0     2.0        1.0
155   62.0      4.0   951.0   7.0  30.0   895.0       2.0     1.0        0.0

[156 rows x 9 columns]

In [57]:
df['Lot'].dtype

dtype('float64')

In [58]:
 df['Lot'].median()

30.0

In [59]:
df['Lot'].fillna(df['Lot'].median, inplace = True)

In [60]:
x = df[['Price']]
x

     Price
0     53.0
1     55.0
2     56.0
3     58.0
4     64.0
..     ...
151   42.0
152   44.0
153   43.0
154   53.0
155   62.0

[156 rows x 1 columns]

In [61]:
y = df[['Lot']]
y

      Lot
0    39.0
1    33.0
2    35.0
3    24.0
4    50.0
..    ...
151  50.0
152  27.0
153  30.0
154  30.0
155  30.0

[156 rows x 1 columns]

In [62]:
x = pd.to_numeric(x, errors='coerce')
y = pd.to_numeric(y, errors='coerce')

plt.plot(x, y, 'b*')
plt.xlabel("Price")
plt.ylabel("Lot")
plt.show()

TypeError: ignored

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size =0.4, random_state = 2)

In [ ]:
lr = LinearRegression()

lr.fit(x_train, y_train)

In [ ]:
y_pred = lr.predict(x_test)
print(r2_score(y_test, y_pred))

In [ ]:
plt.plot(x_train, lr.predict(x_train), color = 'r')
plt.plot(x,y,"b.")
plt.xlabel("x")
plt.ylabel("y")
plt.show()

In [ ]:
poly = PolynomialFeatures(degree = 2, include_bias = True)

x_train_trans = poly.fit_transform(x_train)
x_test_trans = poly.transform(x_test)

In [ ]:
print(x_train[0])
print(x_train_trans[0])

In [ ]:
lr = LinearRegression()
lr.fit(x_train_trans,y_train)

In [ ]:
print(lr.coef_)
print(lr.intercept_)

In [ ]:
x_new = np.linspace(-3,3,200).reshape(200,1)
x_new_poly = poly.transform(x_new)
y_new = lr.predict(x_new_poly)

In [ ]:
plt.plot(x_new, y_new, "r-", linewidth = 2, label = "predictions")
plt.plot(x_train, y_train, "b.", label = "Trainning points")
plt.plot(x_test, y_test, "g.", label = "Testing points")
plt.xlabel("x")
plt.ylabel("y")
plt.legend()
plt.show()